// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomPokemon.Data;

#nullable disable

namespace RandomPokemon.Data.Migrations
{
    [DbContext(typeof(RandomPokemonDbContext))]
    [Migration("20250504081929_UpdateImageSilhouetteOptional")]
    partial class UpdateImageSilhouetteOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("PokemonPokemon", b =>
                {
                    b.Property<int>("EvolutionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvolutionsId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonPokemon");
                });

            modelBuilder.Entity("RandomPokemon.Domain.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PokedexId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Silhouette")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TypeOne")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TypeTwo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonPokemon", b =>
                {
                    b.HasOne("RandomPokemon.Domain.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("EvolutionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandomPokemon.Domain.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
